repos:
  - repo: local
    hooks:
      - id: check-cabal-sync
        name: Check cabal file is in sync with package.yaml
        entry: .github/hooks/check-cabal-sync.sh
        language: script
        stages: [pre-push]
        pass_filenames: false
